### PR TITLE
Request for New Branch: German Translation

### PR DESCRIPTION
**Pull request by erichfi**
The German translation team has initiated work on translating the book. Our updates reside on the 'german-translation' branch in my forked repository.

We request that a new branch, 'german-translation', be created in the base repository. This dedicated branch will facilitate our work and allow us to contribute directly to it.

After the new branch is in place, please change the target of this pull request to 'german-translation'. Then proceed with the merge.

Does this approach work for you? :)

### CODE REVIEW

**Comment by pluralitybook** [comment]
I support this idea and it is what the other translations are leaning towards, but I am checking with my technical folks about potential benefits/challenges of each approach…let me revert to you shortly, but take this as tentative support and you can go ahead if you feel blocked.

 

Best,

Glen

 

Infinite diversity in infinite combinations. (he/him/his)

 <https://www.radicalxchange.org/>

**Comment by pluralitybook** [comment]
I confirmed with the technical team that this makes sense.  It will allow the repo to manage its own governance, which I think is desirable.  We can still create linkages with the governance for the root, but independence as a baseline is a better starting point I think.

 

From: ***@***.*** ***@***.***> 
Sent: Tuesday, June 13, 2023 3:32 PM
To: 'pluralitybook/plurality' ***@***.***>; 'pluralitybook/plurality' ***@***.***>
Cc: 'Mention' ***@***.***>
Subject: RE: [pluralitybook/plurality] Request for New Branch: German Translation (PR #6)

 

I support this idea and it is what the other translations are leaning towards, but I am checking with my technical folks about potential benefits/challenges of each approach…let me revert to you shortly, but take this as tentative support and you can go ahead if you feel blocked.

 

Best,

Glen

 

Infinite diversity in infinite combinations. (he/him/his)

 <https://www.radicalxchange.org/>

**Comment by taipeicityeth** [comment]
hey folks, 

Chiming in from the Traditional Mandarin side, I was going to propose another solution and saw this thread. If there is a desire to standardize the way new translations get created and synced with the website, I thought perhaps sharing here could be useful to get some feedback:

Given the long-term plan to progressively decentralize, would it perhaps make more sense to allow different languages to self-initiate a translation by forking a new repository? 

To solve for Legitimacy and Accessibility, perhaps we can create an "official translations" section under ReadME.md in the original repo that lists each repository for people to access. 

If the way translations are submitted is standardized in the same format, perhaps the website can pull directly from GitHub as well to optimize the workflow even more as new chapters get added and translated

Curious about what you guys think! 

Best,
Jacky

**Comment by pluralitybook** [comment]
I agree with this analysis and we will proceed.  Thank you Jacky!

**Comment by pluralitybook** [comment]
Sure I can do that!

**Comment by pluralitybook** [comment]
Desired repo name?  Perhaps the name you intend in German?  What is that?

**Pull request merged**
