### PR TITLE
Update 02-introduction.md

### PR DESCRIPTION
**Pull request by Omoaholo**
Some edits and an added paragraph with an African and global South perspective.

### CODE REVIEW

**Review by GlenWeyl — APPROVED** [review]
Thanks for the great edits @Omoaholo!

**Comment by GlenWeyl** [comment]
These edits are great, but they have a conflict.  Could you try to resolve?

**Comment by Omoaholo** [comment]
I'll need help at this point.  Three highlights are visible when I click on "Files Changed." Green for the changes that I added; White for unchanged paragraphs and segments; and Pink for the parts I deleted. What does resolving conflict entail and how can one resolve conflicts? When I hover around the "Resolve conflicts" notification on your comment, what I get is "These conflicts are too complex to resolve in the web editor." What's to be done?

**Comment by GlenWeyl** [comment]
I think the simplest thing would be to import to your local copy the all changes that have been made to that chapter and then just insert your changes again and push them to the root.  Likely what occurred is that your version became out of date in someway due to intervening changes and it is now in conflict with the current root.  Sorry about this...


___________________________________________________

Research Lead, Plural Technology Collaboratory<https://aka.ms/plural>, Research Special Projects

___________________________________________________

Collaborate<https://github.com/pluralitybook/plurality> with Digital Minister Audrey Tang, myself and dozens around the world to tell the story of Plurality<https://www.plurality.net/>



________________________________

**Pull request closed without merging**
