### PR TITLE
Add German fork to README

### PR DESCRIPTION
**Pull request by taipeicityeth**

### CODE REVIEW

**Comment by GlenWeyl** [comment]
This PR is based on an out-of-date branch.  Please apply to the current version.

**Comment by taipeicityeth** [comment]
@GlenWeyl, updated, ill make sure to rebase every time, thank you!

**Review by GlenWeyl — APPROVED** [review]
Perfect!

**Comment by taipeicityeth** [comment]
hey @GlenWeyl I believe someone from the team or you will need to merge this PR, thank you!

**Comment by GlenWeyl** [comment]
It still says the branch is out of date...maybe try removing and submitting a new PR?

**Pull request closed without merging**
