### PR TITLE
Update 5-4-augmented-deliberation.md

### PR DESCRIPTION
**Pull request by Identitywoman**
I did some more checking on changes I had submitted...and the paragraph I added about the deliberative processes didn't get added.  (I think I did 3 different small edits so you could see them separately but only one was actually added) 

I just went in and added it again along with key references to the field of processes and tools.

### CODE REVIEW

**Comment by GlenWeyl** [comment]
This is conflicted...I think that was why the other didn't get added as well.  Please make sure you have the write name for the chapter you added.

**Comment by Identitywoman** [comment]
I am really confused Glen. 
I literally started at the front door and went to the page and did the edits. 
I didn't change the name of the chapter. 
These are important edits.

**Comment by GlenWeyl** [comment]
Kaliya,
I have no intention of disregarding your edits or pushing things to one side.  If I have a problem with your edits, I will tell you directly; I have not shied away from this in the past.  You can verify the conflict on GitHub.

Glen


___________________________________________________

Research Lead, Plural Technology Collaboratory<https://aka.ms/plural>, Research Special Projects

___________________________________________________

Collaborate<https://github.com/pluralitybook/plurality> with Digital Minister Audrey Tang, myself and dozens around the world to tell the story of Plurality<https://www.plurality.net/>



________________________________

**Comment by Identitywoman** [comment]
I just re-did the edits.
If it doesn't work again it would be helpful to understand what is wrong
with the edits or how to address whatever is blocking them. .

**Pull request closed without merging**
