### PR TITLE
Tweak language to be more accurate

### PR DESCRIPTION
**Pull request by posix4e**
The use of the term "fractional reserve banking" will be harshly criticized. It's important to realize banks don't lend against reserves and the use of this term isn't needed to make the point we want with the book

### CODE REVIEW

**Review by GlenWeyl — COMMENTED** [review]
I see no technical problems here and will let the review occur through the normal process.

**Review by GlenWeyl — APPROVED** [review]

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Friday, 06-Sep-24 18:14:04 UTC` by Gov4Git `dev`

#### Notice `ksynx5`
Started managing this PR, using the Plural Management Protocol v1, as Gov4Git proposal `1002` with initial __approval score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `6qdu76`
This PR's __approval score__ is now `0.000000`.
The __cost of review__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `sfdm6s`
The set of eligible issues claimed by this PR is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Tuesday, 08-Oct-24 14:32:45 UTC` by Gov4Git `dev`

#### Notice `lwqbc4`
This PR's __approval score__ is now `-20.000000`.
The __cost of review__ is `400.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `3jc2kn`
The set of eligible issues claimed by this PR is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Tuesday, 22-Oct-24 19:57:47 UTC` by Gov4Git `dev`

#### Notice `pi4jvf`
This PR, managed as Gov4Git proposal `1002`, has been rejected 🌂

The PR __approval tally__ was `-20.000000`.

PR __reviewers__ were rewarded:
- Reviewer @glenweyl was rewarded `40.000000` credits

The __cost of review__ of this PR was `400.000000`.

A donation of `360.000000` credits from the __cost of review__ was made to the matching fund.

PR approval tally by reviewer was:
- Reviewer @glenweyl contributed `-20.000000` votes

**Pull request closed without merging**
