### PR TITLE
Fixes Typos Section 4 Completed Issue #848

### PR DESCRIPTION
**Pull request by SamuelVance-Law**
Fixing issue: Typos, Section 4 #848

Claims issue #848 

Am a newbie to GitHub so feedback on errors always appreciated

### CODE REVIEW

**Review by GlenWeyl — APPROVED** [review]
Great work!

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Thursday, 02-May-24 16:47:58 UTC` by Gov4Git `dev`

#### Notice `kfsbn6`
Started managing this PR, using the Plural Management Protocol v1, as Gov4Git proposal `908` with initial __approval score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `ue3oub`
This PR's __approval score__ is now `0.000000`.
The __cost of review__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `tq66hq`
The set of eligible issues claimed by this PR is empty.

**Comment by SamuelVance-Law** [comment]
Thanks! Did both changes go through (4-2 and 4-1)? Or did I make a mistake on 4-1? I had hoped it would come as a separate PR but it is in this one somehow. I promise I'll figure this out eventually....

Screenshot 2024-05-02 at 18 54 31

**Comment by GlenWeyl** [comment]
Both are there!  Can you please, though, add a comment saying "Claims #)" and the issue it claims?  This will allow you to get credit if and when this is approved.

**Comment by SamuelVance-Law** [comment]
> Work in progress fixing issue: Typos, Section 4 #848
> 
> Am a newbie to GitHub so feedback on errors always appreciated

Claims #848

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Thursday, 09-May-24 10:40:57 UTC` by Gov4Git `dev`

#### Notice `nl66v7`
This PR, managed as Gov4Git proposal `908`, has been accepted 🎉

The PR __approval tally__ was `0.000000`.

No issues were claimed by this PR.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Thursday, 09-May-24 10:48:32 UTC` by Gov4Git `dev`

#### Notice `g3x7th`
This PR, managed as Gov4Git proposal `908`, has been accepted 🎉

The PR __approval tally__ was `5.000000`.

No issues were claimed by this PR.

PR __reviewers__ were rewarded:
- Reviewer @glenweyl was rewarded `10.000000` credits

The __cost of review__ of this PR was `25.000000`.

A donation of `15.000000` credits from the __cost of review__ was made to the matching fund.

PR approval tally by reviewer was:
- Reviewer @glenweyl contributed `5.000000` votes

**Pull request merged**
