### PR TITLE
Update 05-04-augmented-deliberation.md

### PR DESCRIPTION
**Pull request by Identitywoman**
Added a sentence about examples of models of deliberation.
This was done in collaboration with Tracy Kunkler - she doesn't have a git hub account (yet)

### CODE REVIEW

**Review by GlenWeyl — APPROVED** [review]
I am going to accept this but will edit it including for typos...

**Comment by GlenWeyl** [comment]
Should I assume you want to share credit with Tracy and she will sign up?

**Comment by Identitywoman** [comment]
I'm going to nudge her to sign up in the coming days.
- Kaliya

**Comment by GlenWeyl** [comment]
Thanks!


___________________________________________________

Research Lead, Plural Technology Collaboratory<https://aka.ms/plural>, Research Special Projects

___________________________________________________

Collaborate<https://github.com/pluralitybook/plurality> with Digital Minister Audrey Tang, myself and dozens around the world to tell the story of Plurality<https://www.plurality.net/>



________________________________

**Comment by Identitywoman** [comment]
Her handle is @bioregionaltracy
https://github.com/bioregionaltracy

**Comment by GlenWeyl** [comment]
Can you either give me an email for her or tell her how to sign up for Gov4Git?


___________________________________________________

Research Lead, Plural Technology Collaboratory<https://aka.ms/plural>, Research Special Projects

___________________________________________________

Collaborate<https://github.com/pluralitybook/plurality> with Digital Minister Audrey Tang, myself and dozens around the world to tell the story of Plurality<https://www.plurality.net/>



________________________________

**Comment by Identitywoman** [comment]
Sure... and Git4Gov was super hard for me...and I'm still not sure I can
actaully use it but I will try.
 Next week when I'm back I will hand hold it through the process.
- Kaliya

**Comment by GlenWeyl** [comment]
The desktop interface or even signing up on GH?


___________________________________________________

Research Lead, Plural Technology Collaboratory<https://aka.ms/plural>, Research Special Projects

___________________________________________________

Collaborate<https://github.com/pluralitybook/plurality> with Digital Minister Audrey Tang, myself and dozens around the world to tell the story of Plurality<https://www.plurality.net/>



________________________________

**Pull request merged**
