### PR TITLE
Added documentation folder, subfolders, and existing docs

### PR DESCRIPTION
**Pull request by gardenenigma**
- Added documentation folder and subfolders. Added existing content from notion, and the wiki as .md (and .png) files within the subfolders.
- Next step is to start building out documentation as needed and iterate on content organisation/folder structure as new docs are added.

### CODE REVIEW

**Review by GlenWeyl — CHANGES_REQUESTED** [review]
This is absolutely phenomenal work!  Just one problem: the label you have people suggest for having their issue managed by gov4git is actually the old one...the current one is gov4git:pmp-v1.  Mind updating and resubmitting?

**Comment by GlenWeyl** [comment]
Also please join Gov4Git so I can reward you for this huge contribution!

**Comment by gardenenigma** [comment]
The issue has been resolved, and the image 'gov4git-how-it-works.png' now shows the gov4git:pmp-v1 label.

I should note, this image was not created by myself. I took it from the Gov4Git github repo: https://github.com/gov4git/gov4git/tree/v2/doc/images

**Review by GlenWeyl — APPROVED** [review]
This is great, now please join Gov4Git yourself so I can give you credit!

**Pull request merged**
