### PR TITLE
Update 3-1-living-in-a-⿻-world.md

### PR DESCRIPTION
**Pull request by Omoaholo**
As presently rendered, the reference to this simplified Edward Lorenz experiment when critically examined could come across to scientists as an exaggeration of a metaphor.

### CODE REVIEW

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Tuesday, 09-Apr-24 19:54:54 UTC` by Gov4Git `dev`

#### Notice `vzubit`
Started managing this PR, using the Plural Management Protocol v1, as Gov4Git proposal `863` with initial __approval score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `tk2izy`
This PR's __approval score__ is now `0.000000`.
The __cost of review__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `sndk5r`
The set of eligible issues claimed by this PR is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Monday, 29-Apr-24 18:38:03 UTC` by Gov4Git `dev`

#### Notice `fp2aya`
This PR's __approval score__ is now `-7.000000`.
The __cost of review__ is `49.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `5ddbb4`
The set of eligible issues claimed by this PR is empty.

**Comment by GlenWeyl** [comment]
This proposal has now been open for a while, so I am going to close it as it has negative votes.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Monday, 12-Aug-24 06:00:43 UTC` by Gov4Git `dev`

#### Notice `ho4nbg`
This PR, managed as Gov4Git proposal `863`, has been rejected 🌂

The PR __approval tally__ was `-7.000000`.

PR __reviewers__ were rewarded:
- Reviewer @glenweyl was rewarded `14.000000` credits

The __cost of review__ of this PR was `49.000000`.

A donation of `35.000000` credits from the __cost of review__ was made to the matching fund.

PR approval tally by reviewer was:
- Reviewer @glenweyl contributed `-7.000000` votes

**Pull request closed without merging**
