### PR TITLE
Added footnote, re: Multi-source validation

### PR DESCRIPTION
**Pull request by SamRoizen**

### CODE REVIEW

**Review by GlenWeyl — APPROVED** [review]
This is positive and I see no problem approving it, though it would be even better if it could highlight how plural thinking aligns with this idea.  Does this claim an open issue for credit?

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Wednesday, 11-Dec-24 18:44:04 UTC` by Gov4Git `dev`

#### Notice `z7ec3j`
Started managing this PR, using the Plural Management Protocol v1, as Gov4Git proposal `1042` with initial __approval score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `twolck`
This PR's __approval score__ is now `0.000000`.
The __cost of review__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `niojz7`
The set of eligible issues claimed by this PR is empty.

**Comment by SamRoizen** [comment]
Yes, #1017

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Tuesday, 17-Dec-24 16:52:09 UTC` by Gov4Git `dev`

#### Notice `aptdxm`
This PR's __approval score__ is now `5.000000`.
The __cost of review__ is `25.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `qkgfgt`
The set of eligible issues claimed by this PR is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Saturday, 21-Dec-24 20:13:47 UTC` by Gov4Git `dev`

#### Notice `pplbvk`
This PR, managed as Gov4Git proposal `1042`, has been accepted 🎉

The PR __approval tally__ was `5.000000`.

No issues were claimed by this PR.

PR __reviewers__ were rewarded:
- Reviewer @glenweyl was rewarded `10.000000` credits

The __cost of review__ of this PR was `25.000000`.

A donation of `15.000000` credits from the __cost of review__ was made to the matching fund.

PR approval tally by reviewer was:
- Reviewer @glenweyl contributed `5.000000` votes

**Pull request merged**
