### PR TITLE
Added Common Good AI and CrowdSmart to 5-4-augmented-deliberation.md

### PR DESCRIPTION
**Pull request by vicstanski**

### CODE REVIEW

**Review by GlenWeyl — APPROVED** [review]
I don't see any technical problems here, but will need to be reviewed for merit by community.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Tuesday, 30-Jul-24 17:49:27 UTC` by Gov4Git `dev`

#### Notice `2i6t54`
Started managing this PR, using the Plural Management Protocol v1, as Gov4Git proposal `960` with initial __approval score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `tyhfcw`
This PR's __approval score__ is now `0.000000`.
The __cost of review__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `yrcb5z`
The set of eligible issues claimed by this PR is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Thursday, 01-Aug-24 18:50:17 UTC` by Gov4Git `dev`

#### Notice `izct3f`
This PR's __approval score__ is now `-9.000000`.
The __cost of review__ is `81.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `lpy25a`
The set of eligible issues claimed by this PR is empty.

**Comment by GlenWeyl** [comment]
While I appreciate the contribution, I feel this is too long on a single proprietary project and was not preceded by a community conversation around the issue being addressed.  It has negative votes now so I am going to close it.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Monday, 12-Aug-24 06:00:43 UTC` by Gov4Git `dev`

#### Notice `l24k3s`
This PR, managed as Gov4Git proposal `960`, has been rejected 🌂

The PR __approval tally__ was `-9.000000`.

PR __reviewers__ were rewarded:
- Reviewer @glenweyl was rewarded `18.000000` credits

The __cost of review__ of this PR was `81.000000`.

A donation of `63.000000` credits from the __cost of review__ was made to the matching fund.

PR approval tally by reviewer was:
- Reviewer @glenweyl contributed `-9.000000` votes

**Comment by vicstanski** [comment]
Hello Glen,

Thank you for your note.  To ensure we understand and adhere to how the
submission process works, a few quick followup questions for clarification:

Regarding the length of the submission, we can easily shorten it. We want
to be consistent with the desired format.

Also, is it necessary to be open source? We had not realized this given
that, for example, Remesh is included.
CrowdSmart is opening up its APIs and Common Good AI will use these open
APIs.

All code developed at Common Good AI will be open source.

We would be glad to include this information in the GitHub entry. Please
let us know if you’d like us to resubmit a shorter version and include
these specific points.

(Also - ww wanted to clarify that we don't have community points because we
don't currently use GitHub.)

We love that you are documenting the full landscape of augmented
deliberation, which we are a part of. We are excited to collaborate with
all stakeholders to move forward this important work together.

All the best,
Victoria

**Comment by vicstanski** [comment]
Victoria,
Thanks for writing!
There are extensive guidelines for contribution here: https://github.com/pluralitybook/plurality/blob/main/docs/contributing/Beginners%20contribution%20guide.md
In terms of length, there is nothing hard and fast.  The community (in theory) decides on any contribution and can decide as it wants.  In the case of your submission, the only community member who voted on it after a week plus was me, so effectively I decided to reject it.  I guess my criteria is ensuring that length and attention to projects is roughly proportional to some combination of their alignment of the ideas to the core tenets of the book and especially their ability to illustrate aspects of the conceptual framework that other examples do not illustrate, the real-world impact they have had, etc.  I would look at other examples of things we mention, how much airtime they are getting and how well they fit those criteria and try to keep your length similar to them.  Open source is definitely one tenet and the fact that your product is not open source and is connected to a for-profit product definitely inclines me to shortening its mention, but not to eliminating it.
If you want to receive credit for your submission and to ensure it has community support before making it in full, you can submit an issue explaining the general topic and why it would be good to add, which the community can then prioritize.  This way you can “limit the risk” you face to whether you faithfully execute on the issue.  In terms of receiving community points, you can do this precisely by submitting an issue, having it prioritized and then addressing it.  You can also receive a few for a proof-of-purchase image of the book, if you have purchased it, or for a donation to the community.
Will have more amazing examples of augmented deliberation coming in the next few weeks, as we learned of on our world tour.

Best,
Glen

**Pull request closed without merging**
