### PR TITLE
Fixed Typos Section 7 - Issue #846

### PR DESCRIPTION
**Pull request by byteofpython**
Claims #846

### CODE REVIEW

**Comment by GlenWeyl** [comment]
Must resolve conflicts before we can consider

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Wednesday, 29-May-24 07:08:51 UTC` by Gov4Git `dev`

#### Notice `puyejr`
Started managing this PR, using the Plural Management Protocol v1, as Gov4Git proposal `919` with initial __approval score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `cayus4`
This PR's __approval score__ is now `0.000000`.
The __cost of review__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `cojjdh`
The set of eligible issues claimed by this PR is empty.

**Review by GlenWeyl — APPROVED** [review]

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Thursday, 30-May-24 06:22:40 UTC` by Gov4Git `dev`

#### Notice `tv2zjc`
This PR's __approval score__ is now `15.000000`.
The __cost of review__ is `225.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `gotqfq`
The set of eligible issues claimed by this PR is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Sunday, 09-Jun-24 17:19:12 UTC` by Gov4Git `dev`

#### Notice `qzdnnf`
This PR, managed as Gov4Git proposal `919`, has been accepted 🎉

The PR __approval tally__ was `15.000000`.

No issues were claimed by this PR.

PR __reviewers__ were rewarded:
- Reviewer @glenweyl was rewarded `30.000000` credits

The __cost of review__ of this PR was `225.000000`.

A donation of `195.000000` credits from the __cost of review__ was made to the matching fund.

PR approval tally by reviewer was:
- Reviewer @glenweyl contributed `15.000000` votes

**Pull request merged**
