### PR TITLE
People's bid description 

### PR DESCRIPTION
**Pull request by dduncanmccourt**
Issue that this PR claims: 
- claims https://github.com/pluralitybook/plurality/issues/1012

### CODE REVIEW

**Review by GlenWeyl — APPROVED** [review]
I'll let voting proceed on this, but will probably make a PR myself if it is approved to integrate the style a bit more and make it seem less of a clear plug.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Tuesday, 08-Oct-24 14:09:28 UTC` by Gov4Git `dev`

#### Notice `3hm5by`
Started managing this PR, using the Plural Management Protocol v1, as Gov4Git proposal `1024` with initial __approval score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `tctvbl`
This PR referenced https://github.com/pluralitybook/plurality/issues/1012, managed as Gov4Git concern `1012`.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Tuesday, 08-Oct-24 14:32:46 UTC` by Gov4Git `dev`

#### Notice `uvyq7g`
This PR's __approval score__ is now `10.000000`.
The __cost of review__ is `100.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `ake4it`
The set of eligible issues claimed by this PR is empty.


#### Notice `i6oq2a`
This PR's __approval score__ is now `10.000000`.
The __cost of review__ is `100.000000`.
The __projected bounty__ is now `2500.000000`.

#### Notice `p5ipwg`
The set of eligible issues claimed by this PR changed:
- https://github.com/pluralitybook/plurality/issues/1012, managed as Gov4Git motion `1012` with community attention of `2500.000000`

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Tuesday, 22-Oct-24 19:57:48 UTC` by Gov4Git `dev`

#### Notice `k7rig6`
This PR, managed as Gov4Git proposal `1024`, has been accepted 🎉

The PR __approval tally__ was `223.606798`.

Resolved issues:
- [Issue #1012](https://github.com/pluralitybook/plurality/issues/1012)

The __cost of priority__ of issues claimed by this PR (the cost of prioritization) was `2500.000000`.

The __projected bounty__, after matching, for the author of this PR was `2500.000000`.

A __donation__ of `2500.000000` credits from the __cost of priority__ was made to the matching fund.

PR __reviewers__ were rewarded:
- Reviewer @glenweyl was rewarded `100.000000` credits

The __cost of review__ of this PR was `100.000000`.

PR approval tally by reviewer was:
- Reviewer @glenweyl contributed `223.606798` votes

**Pull request merged**
