### PR TITLE
Copyedits

### PR DESCRIPTION
**Pull request by techxorcist**
The edits are largely fixes to typos or errors in references that should be straightforward. In a few cases, the edits suggest changes in punctuation or word choice for readability and are more discretionary.

### CODE REVIEW

**Review by GlenWeyl — APPROVED** [review]
All look good to me, awaiting GitRules determination.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Monday, 29-Jul-24 20:39:24 UTC` by Gov4Git `dev`

#### Notice `jz7sff`
Started managing this PR, using the Plural Management Protocol v1, as Gov4Git proposal `957` with initial __approval score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `kl6s6b`
This PR's __approval score__ is now `0.000000`.
The __cost of review__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `kvjvf3`
The set of eligible issues claimed by this PR is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Thursday, 01-Aug-24 18:50:16 UTC` by Gov4Git `dev`

#### Notice `xkkjjf`
This PR's __approval score__ is now `12.000000`.
The __cost of review__ is `144.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `nnzve6`
The set of eligible issues claimed by this PR is empty.

**Comment by GlenWeyl** [comment]
Please address conflicts @techxorcist and you have approval.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Friday, 23-Aug-24 05:53:14 UTC` by Gov4Git `dev`

#### Notice `7h3bhr`
This PR's __approval score__ is now `362.000000`.
The __cost of review__ is `122644.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `ng6hlb`
The set of eligible issues claimed by this PR is empty.

**Comment by GlenWeyl** [comment]
There are conflicts that need to be resolved, but then happy to merge this.

**Comment by techxorcist** [comment]
Thank you @GlenWeyl. I have resolved the conflicts.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Friday, 13-Dec-24 14:40:03 UTC` by Gov4Git `dev`

#### Notice `wx2z6i`
This PR, managed as Gov4Git proposal `957`, has been accepted 🎉

The PR __approval tally__ was `362.000000`.

No issues were claimed by this PR.

PR __reviewers__ were rewarded:
- Reviewer @glenweyl was rewarded `24.000000` credits
- Reviewer @shaudub was rewarded `700.000000` credits

The __cost of review__ of this PR was `122644.000000`.

A donation of `121920.000000` credits from the __cost of review__ was made to the matching fund.

PR approval tally by reviewer was:
- Reviewer @glenweyl contributed `12.000000` votes
- Reviewer @shaudub contributed `350.000000` votes

**Pull request merged**
