### PR TITLE
Added possible yushan chapter reorg

### PR DESCRIPTION
**Pull request by vbuterin**

### CODE REVIEW

**Review by pluralitybook — COMMENTED** [review]
Given that @giselechou and @audreyt have primary lead here, I'll leave it to them to respond.  I also sent them a possible outline that can be reconciled with this as you all wish.

**Comment by audreyt** [comment]
Glen's possible outline has been translated and merged to the main branch — would you like to resolve the conflict first so we can merge the edits? Could be as simple as moving the gold card paragraphs into the appropriate section ("Moving Forward")

**Comment by giselechou** [comment]
@vbuterin  
Hello 你好，
可以參考這個連結：https://hackmd.io/_doIKl2dStK6BUYnq5WwSA
在金卡部分的引述希望可以作為投稿文，先放在「前行（Forward)」session, 我另撰寫了華文版。

P.S. 
第一段落、第三段落 重新編譯的部分比較多-> 請參考
也建議在第二段落，可以增加關於 "Hypercerts" 和  "Tea" 項目的理念。
我們也可以直接用Hackmd協作，謝謝～

**Comment by GlenWeyl** [comment]
superseded by your later reorg.

**Pull request closed without merging**
