### PR TITLE
Fixed Typo Section 1: Preface, 1 Seeing Plural #841 & Fixed Typos Section 2 #844

### PR DESCRIPTION
**Pull request by byteofpython**
Claims #841

First PR, hope this works as intended!

### CODE REVIEW

**Review by GlenWeyl — APPROVED** [review]

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Friday, 03-May-24 23:10:58 UTC` by Gov4Git `dev`

#### Notice `ugfzx6`
Started managing this PR, using the Plural Management Protocol v1, as Gov4Git proposal `910` with initial __approval score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `uuyjrr`
This PR's __approval score__ is now `0.000000`.
The __cost of review__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `amjz62`
The set of eligible issues claimed by this PR is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Friday, 03-May-24 23:37:26 UTC` by Gov4Git `dev`

#### Notice `o62jxk`
Started managing this PR, using the Plural Management Protocol v1, as Gov4Git proposal `910` with initial __approval score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `no7a3b`
This PR's __approval score__ is now `0.000000`.
The __cost of review__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `2ekzcn`
The set of eligible issues claimed by this PR is empty.

**Comment by byteofpython** [comment]
Claims #844

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Thursday, 09-May-24 10:14:38 UTC` by Gov4Git `dev`

#### Notice `eq4lx2`
This PR's __approval score__ is now `7.000000`.
The __cost of review__ is `49.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `cnsjzz`
The set of eligible issues claimed by this PR is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Thursday, 09-May-24 10:40:58 UTC` by Gov4Git `dev`

#### Notice `pf3omg`
This PR's __approval score__ is now `7.000000`.
The __cost of review__ is `49.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `nij3y5`
The set of eligible issues claimed by this PR is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Tuesday, 14-May-24 01:07:39 UTC` by Gov4Git `dev`

#### Notice `cz4d52`
This PR's __approval score__ is now `29.000000`.
The __cost of review__ is `533.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `auavew`
The set of eligible issues claimed by this PR is empty.

**Comment by GlenWeyl** [comment]
You are approved, but there are now conflicts.  Please resolve these and I will merge.

**Comment by byteofpython** [comment]
> You are approved, but there are now conflicts. Please resolve these and I will merge.

Sorry, done.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Thursday, 16-May-24 13:24:39 UTC` by Gov4Git `dev`

#### Notice `zricqn`
This PR, managed as Gov4Git proposal `910`, has been accepted 🎉

The PR __approval tally__ was `29.000000`.

No issues were claimed by this PR.

PR __reviewers__ were rewarded:
- Reviewer @glenweyl was rewarded `14.000000` credits
- Reviewer @shaudub was rewarded `44.000000` credits

The __cost of review__ of this PR was `533.000000`.

A donation of `475.000000` credits from the __cost of review__ was made to the matching fund.

PR approval tally by reviewer was:
- Reviewer @glenweyl contributed `7.000000` votes
- Reviewer @shaudub contributed `22.000000` votes

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Thursday, 16-May-24 13:41:08 UTC` by Gov4Git `dev`

#### Notice `s6tj5b`
This PR, managed as Gov4Git proposal `910`, has been accepted 🎉

The PR __approval tally__ was `29.000000`.

No issues were claimed by this PR.

PR __reviewers__ were rewarded:
- Reviewer @glenweyl was rewarded `14.000000` credits
- Reviewer @shaudub was rewarded `44.000000` credits

The __cost of review__ of this PR was `533.000000`.

A donation of `475.000000` credits from the __cost of review__ was made to the matching fund.

PR approval tally by reviewer was:
- Reviewer @glenweyl contributed `7.000000` votes
- Reviewer @shaudub contributed `22.000000` votes

**Pull request merged**
