### PR TITLE
Fixes Typos, Section 7 #846

### PR DESCRIPTION
**Pull request by SamuelVance-Law**
Claims Issue #846

### CODE REVIEW

**Comment by GlenWeyl** [comment]
@SamuelVance-Law, thanks for these.  You have some conflicts that need to be resolved before this can be considered.

**Review by GlenWeyl — APPROVED** [review]
All seems helpful to me!  Awaiting GitRules determination.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Monday, 29-Jul-24 20:39:24 UTC` by Gov4Git `dev`

#### Notice `b7675p`
Started managing this PR, using the Plural Management Protocol v1, as Gov4Git proposal `954` with initial __approval score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `cg4eny`
This PR's __approval score__ is now `0.000000`.
The __cost of review__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `2baabg`
The set of eligible issues claimed by this PR is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Wednesday, 31-Jul-24 03:08:50 UTC` by Gov4Git `dev`

#### Notice `75q6og`
This PR's __approval score__ is now `3.000000`.
The __cost of review__ is `9.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `p7ljxv`
The set of eligible issues claimed by this PR is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org">This project is governed with Gov4Git.</a> Gov4Git notices
On `Friday, 02-Aug-24 13:15:45 UTC` by Gov4Git `dev`

#### Notice `7usshq`
This PR, managed as Gov4Git proposal `954`, has been accepted 🎉

The PR __approval tally__ was `3.000000`.

No issues were claimed by this PR.

PR __reviewers__ were rewarded:
- Reviewer @audreyt-gov4git was rewarded `6.000000` credits

The __cost of review__ of this PR was `9.000000`.

A donation of `3.000000` credits from the __cost of review__ was made to the matching fund.

PR approval tally by reviewer was:
- Reviewer @audreyt-gov4git contributed `3.000000` votes

**Pull request merged**
