### PR TITLE
figs: fix cropping on a few images

### PR DESCRIPTION
**Pull request by ccerv1**

### CODE REVIEW

**Review by GlenWeyl — APPROVED** [review]
Thank you!  Would you mind also taking figure labels/legends off any figures still containing them so they all conform to your style?

**Comment by ccerv1** [comment]
> Thank you! Would you mind also taking figure labels/legends off any figures still containing them so they all conform to your style?

Sure - happy to. Do you have a recent example in mind just so I know exactly what you're referring to?

**Comment by GlenWeyl** [comment]
https://github.com/pluralitybook/plurality/blob/main/figs/private.png
That may now be superceded by something you made...but if it is, it would be awesome if you would consider making a PR that actually inserts references to the charts into the text and includes captions in the format prescribed by the style guide (and possibly refine the style guide to give sharper guidance) so everything fits together:
https://github.com/pluralitybook/plurality/blob/main/docs/Style%20Guide.md
Note that as the sample I linked to this obviously messed up diagram, sorry if that's confusing.



___________________________________________________

Research Lead, Plural Technology Collaboratory<https://aka.ms/plural>, Research Special Projects

___________________________________________________

Collaborate<https://github.com/pluralitybook/plurality> with Digital Minister Audrey Tang, myself and dozens around the world to tell the story of Plurality<https://www.plurality.net/>



________________________________

**Comment by ccerv1** [comment]
@GlenWeyl confirming it should be like this: 

image

**Pull request merged**
